---
- name: Include Vars
  include_vars:
    file: "{{ playbook_dir + '/clients/' + target }}"

- name: Create RouterOS configuration file
  template:
    src: config.j2
    dest: "/home/mrcirca/{{target}}_config"
